rabbitmq:
  user: admin
  pass: admin
  host: 206.81.26.50
  port: 5672
  queues:
    consumer: profitEventDev
    producer: dbEventQueueRep

scylladb:
  user: pineyewss
  pass: 12345@Pineye
  host: 206.81.26.50
  port: 9042
  keyspace: pineyewss

server:
  host: localhost
  socket_port: 8083
  http_port: 8081

redis:
  host: 206.81.26.50
  port: 6379
  pass: ""
