rabbitmq:
  user: admin
  pass: admin
  host: localhost
  port: 5672
  queues:
    consumer: profitEventDev
    producer: dbEventQueue

scylladb:
  user: pineyewss
  pass: your_password
  host: localhost
  port: 9042
  keyspace: pineyewss

server:
  host: localhost
  socket_port: 5000
  http_port: 8081

redis:
  host: localhost
  port: 6379
  pass: ""
